version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - aws --version
    - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 860061945305.dkr.ecr.us-west-2.amazonaws.com
    - IMAGE_NAME=sumagna-pension-management
    - IMAGE_URI=860061945305.dkr.ecr.us-west-2.amazonaws.com/sumagna-pension-management:latest
    - CONTAINER_NAME=pension-management
  build:
    commands:
    - echo Build started on `date`
    - echo $IMAGE_NAME
    - mvn clean package -Ddockerfile.skip
    - docker build -t $IMAGE_NAME .
  post_build:
    commands:
    - echo Build completed on `date`
    - echo $(docker images)
    - docker tag $IMAGE_NAME $IMAGE_URI
    - echo Pushing docker image
    - docker push $IMAGE_URI
    - echo push completed
    - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $IMAGE_URI > imagedefinitions.json
artifacts:
  files:
  - imagedefinitions.json
  - target/eurekaserver.jar